import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import Link from "next/link";

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const session = await auth();

	return (
		<html lang="en">
			<body className={inter.className}>
				<Link href="/dashboard">dasboard</Link>
				<Link href="/dashboard">blog</Link>
				<Link href="/dashboard">auth</Link>
				<SessionProvider session={session}>{children}</SessionProvider>
			</body>
		</html>
	);
}
